### ISSUE TITLE
List of top visited metro areas not showing up

### ISSUE THREAD

**Issue by ozanj** [ozanj/naed_presentation#12]
@cyouh95 

on deep diver results, the slide for top visited metro areas is blank.

**Comment by cyouh95** [comment]
@ozanj I think this is because of the library used to load the csv data into the tables, which requires us to start a local webserver. If you have Python installed, you could run `python3 -m http.server` and then view the slides at http://localhost:8000/index.html. But the tables should show up in the published version [here](https://ozanj.github.io/naed_presentation)!

**Comment by ozanj** [comment]
hmm. you may have to walk me through this tomorrow.

**Comment by cyouh95** [comment]
@ozanj I think this R package might work! https://github.com/yihui/servr We can run `servr::httd()` in the RStudio console and the slides should be at: http://127.0.0.1:4321
